Completo o Ex. 1
BrunaGPires/Learn4Elixir pull request #1
Opened 2023-10-19 00:04 UTC by BrunaGPires

### Solução do Livebook Nº 1

cc @anabastos @camilotk @cherryramatisdev @cyytrus @digzom @douglastofoli @eulixir @lanjoni @OtavioSC @zoedsoupe

2023-10-19 23:05 UTC, OtavioSC requested changes
Vou deixar em aberto a PR, mas se quiser prosseguir para as próximas listas me avise que eu aprovo 😃

2023-10-19 23:05 UTC, OtavioSC commented on chapters/chapter1.livemd
> +comentario =
Olá, parabéns 🎆 você seguiu um bom caminho e chegou na resolução dos exercícios, mas gosto de pontuar para todos que seria interessante tentar resolver utilizando o Pattern Matching (casamento de padrões) do Elixir, como você fez ao resgatar o primeiro comentário. Mas assim, é apenas uma recomendação para testar como funcionaria nesse formato, fique livre se quiser tentar 😃

2023-10-23 11:31 UTC, eulixir commented
Opa @BrunaGPires, como vai?

Passando aqui só para lembrar de colocar a tag do hacktoberfest :)

2023-10-24 04:52 UTC, BrunaGPires commented on chapters/chapter1.livemd
> +comentario =
Olá, valeu! Acho que agora consegui resolver o exercício usando Pattern Matching.

2023-10-25 13:03 UTC, OtavioSC approved these changes
Bom trabalho @BrunaGPires

2023-10-25 13:59 UTC, merged